<?xml version="1.0"?>
<package format="2">
  <name>maxt_pkg</name>
  <version>0.2.0</version>
  <description>Basic MAVROS flight actions orchestrated with BehaviorTree.CPP.</description>

  <maintainer email="user@example.com">User</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>behaviortree_cpp_v3</depend>
  <depend>geometry_msgs</depend>
  <depend>mavros_msgs</depend>
  <depend>roscpp</depend>
  <depend>tf2</depend>

  <exec_depend>mavros</exec_depend>

  <export>
    <build_type>catkin</build_type>
  </export>
</package>
